#构造工具
V:=@	
CC:=gcc
LD:=ld
MAKE:=make -C
ASM:=nasm
OBJDUMP:=objdump
OBJCOPY:=objcopy

#工程目录
ROOT_DIR:="/home/fenghan/fh_os"
INCLUDE_DIR:=$(ROOT_DIR)
SUB_DIR:=boot\
		kernel

#运行工具
QEMU:=qemu-system-x86_64
IMAGE:=kernel.img
GDBPORT=12345

#参数配置
C_FLAGS:= -Werror -g -m32 -O1 -fno-builtin -nostdinc -static -fno-omit-frame-pointer -std=gnu99 -I$(INCLUDE_DIR)
LD_FLAGS:=-Bstatic -m elf_i386
QEMU_FLAGS:=-drive file=$(IMAGE),media=disk,format=raw -serial mon:stdio -gdb tcp::$(GDBPORT) -m 1G

